### ISSUE TITLE
[support] Cannot connect metamask on cosmos bridge <ticket-9267>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#387] opened 2023-09-06 17:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Any EVM
- Source Chain Wallet: Metamask
- Target Chain: OSMOSIS
- Target Chain Wallet: Kepler
- Asset Type:
- Tx:
```

### Current Behavior

On clicking on "connect wallet" on the cosmos bridge it shows "install metamask" even though the user already have metamask installed.
The user tried connecting to metamask on the token bridge and it worked as expected.

![cosmos issue](https://github.com/XLabs/portal-bridge-ui/assets/64994788/f0186599-3030-4f0d-9f38-b7902f11d616)
![cosmos_devtools_log](https://github.com/XLabs/portal-bridge-ui/assets/64994788/0e99c279-e24d-4366-b466-95b34254999d)

### Steps To Reproduce

CONNECT METAMASK WALLET ON COSMOS BRIDGE

### Anything else?

The user was able to Kepler wallet but could not connect to both Rabby and Metamask wallets on the Cosmos bridge. However, i was able to connect to the wallets on my end.

**Comment by sebastianscatularo** [comment] 2023-09-06 17:30
@drisAloma has the user tried re-installing Metamask, I've connected Metamask successfully multiple times on cosmos bridge

https://github.com/XLabs/portal-bridge-ui/assets/1277510/631d158e-6781-4324-b68e-7c95d027fdc0

**Comment by drisAloma** [comment] 2023-09-06 17:42
No, only hard refresh and clearing browser's cache, I will suggest that to the user now.

Exactly, I was able to do the same multiple times on my end as well.

**Comment by drisAloma** [comment] 2023-09-06 18:31
The user tried reinstalling metamask but still having the same issue.

**Comment by drisAloma** [comment] 2023-09-06 19:38
This user's console log is showing this now as well


![chains_rpcs](https://github.com/XLabs/portal-bridge-ui/assets/64994788/b5bd45c4-8c24-4063-bdfe-4a3b11d506c5)

![rpcs_wormhole-connect](https://github.com/XLabs/portal-bridge-ui/assets/64994788/6dd1cc13-1700-4936-93ce-263b8c3ce7c6)

**Comment by sebastianscatularo** [comment] 2023-09-07 02:58
Yes, everything looks good. This seems to be an error on the user's side. The user should try with a different browser or disabling other extensions and reinstalling Metamask. There is not much to do on our side. If more than one user is able to connect using Metamask, then the issue is not on the bridge's side.

**Comment by sebastianscatularo** [comment] 2023-09-07 03:00
Wormhole Connect logs the suggestions as errors, but they are not errors. We do not have dedicated RPCs for all the chains, that's why those logs are raised.

**Comment by drisAloma** [comment] 2023-09-07 17:03
Right.
Okay, noted!
Thank you @sebastianscatularo

**Comment by yuli-ferna** [comment] 2023-09-18 13:36
In addition to everything that was discussed, I leave this test that I did, as we failed to replicate it and it seems something on the user's side, I will close this topic for now.



https://github.com/XLabs/portal-bridge-ui/assets/35125931/26073da8-012a-440f-9eff-d8441b3230a6

**Closed by yuli-ferna** 2023-09-18 13:36 UTC
Labels: medium, needs triage, wormhole-support
