### ISSUE TITLE
Ethereum -> Algorand not working when using WalletConnect in both source and destination

### ISSUE THREAD

**Issue by d13co** [XLabs/portal-bridge-ui#81] opened 2023-04-23 21:42 UTC
## Steps to reproduce

1. Connect Ethereum source account with WalletConnect
2.  Choose token, amount
3. Start connecting Algorand destination account with WalletConnect (i.e. Pera or Defly)

## Experienced behavior

The page is replaced by the error message "An unexpected error has occurred. Please refresh the page." 

![1682263499](https://user-images.githubusercontent.com/95573415/233849477-275864a5-3fa3-4779-9ccf-c4d47e80f244.png)

## Expected behavior

Pera Connect / Defly Connect modal shows and I can proceed to connect my account

## Solution recommendation

![1682263484](https://user-images.githubusercontent.com/95573415/233849472-6cb3e00d-2426-429e-9922-85b034727427.png)

The console logs "address seems to be malformed", which is the algorand SDK error when an address provided to the SDK is not a valid Algorand address

This leads me to believe that the source and destination WalletConnect sessions are not independent as they should, but instead the EVM address (0x12357890123...) from the source session is being fed into the algorand SDK, causing this error.

**Comment by sebastianscatularo** [comment] 2023-04-24 02:22
@d13co thank you for reporting it, we are going to investigate it, and keep you posted.

**Comment by M-Picco** [comment] 2023-04-24 13:07
@d13co Thanks for reporting the issue. Indeed the cause seems to be a conflict between sessions since neither of them configures a different storage id, so they try to access the same key. I've added a default setting to the evm wallet connect connector to prevent this, but I fear neither Pera nor Defly currently allow it to be set.

**Comment by M-Picco** [comment] 2023-04-24 13:48
@d13co The fix should be deployed. Could you try again please?

**Comment by d13co** [comment] 2023-04-28 01:28
Bump. Could you take a look? Is it better to open another issue?

**Comment by sebastianscatularo** [comment] 2023-04-28 03:45
Hi, @d13co thank you for the head up, we will be reviewing it as soon as possible, and we'll keep you posted. I've created another issue to track it, please refer to it for future updates. I'm going to close it, due to, my understanding the initial issue was fixed.

**Closed by sebastianscatularo** 2023-04-28 03:45 UTC
