### ISSUE TITLE
[Bug] Cannot redeem token to Polygon, Optimism using Phantom <ticket-8095 & 9142>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#325] opened 2023-08-18 20:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Polygon
- Source Chain Wallet: Metamask
- Target Chain: Solana
- Target Chain Wallet: Phantom
- Asset Type: Token
- Tx: https://polygonscan.com/tx/0x02d1ad0c4bf987963835411929dc8b55ff32ef8f1c4120ab558302c21d90a73a
- Token: tBTC
```

### Current Behavior

The user (and I also tried the redeem workflow) got the notification information on the fourth transaction to approve.

![solana_ish](https://github.com/XLabs/portal-bridge-ui/assets/64994788/4844aeeb-7b5e-497b-9fc4-cc2f4dc95902)

### Steps To Reproduce

Redeem workflow

### Anything else?

.The token account information shows wormhole_gateway; https://solscan.io/account/87MEvHZCXE3ML5rrmh5uX1FbShHmRXXS32xJDGbQ7h5t

The user later tried sending the same token an hour later, it went through and was redeemed sucessfully.

**Comment by sebastianscatularo** [comment] 2023-08-22 14:35
@drisAloma tBTC flow is different than other flows because tBTC for:

- polygon
- base
- arbitrum
- optimism 
- solana

is not the Wrapped version from the Token Bridge contract, that's why the "Recipient Address" is the wormhole_gateway contract, that takes the Wrapped Version and emits the Threshold tBTC version.

Regarding the simulation failure, could be due to a network issue, not sure, if the user was able to bridge, seems to me, it is working as expected. We have in backlog some tasks to add more information on tBTC assets.

**Comment by sebastianscatularo** [comment] 2023-08-22 14:51
the user was able to send it, so, I'm going to close this @drisAloma, if there is another report, we could re-open it

**Comment by drisAloma** [comment] 2023-08-23 10:09
Okay, noted, thank you @sebastianscatularo 
I have also tried redeeming it on my end for the user with different internet services but got the same simulation failure message.

**Comment by sebastianscatularo** [comment] 2023-08-25 14:39
do you have the tx hash on the failing transfer?

**Comment by drisAloma** [comment] 2023-08-29 18:53
Hello @sebastianscatularo 
The same user is having similar issue again with another transaction from another chain (optimism). I tried redeeming it and got the same error message: "transaction(s) reverted during simulation".

Tx: https://optimistic.etherscan.io/tx/0x5fb4a0f0c591a6b4dc6ca2aae771e3162e194bfbb67091af59c75db6140e69f7
Target chain: Solana

**Comment by SamantaCasal** [comment] 2023-08-29 20:16
Tested from: https://www.portalbridge.com/#/transfer
FYI: @sebastianscatularo 
The Tx: https://optimistic.etherscan.io/tx/0x5fb4a0f0c591a6b4dc6ca2aae771e3162e194bfbb67091af59c75db6140e69f7
It is found and available for redeem. 
Evidence: 
https://github.com/XLabs/portal-bridge-ui/assets/69044575/14b9502e-69a6-48cb-9b1d-9a6052d1df28

![Screenshot 2023-08-29 at 5 09 54 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/06cc950c-8476-4a86-aca2-97b38ad8408b)

**Comment by sebastianscatularo** [comment] 2023-08-29 20:35
@drisAloma, it seems the issue is on the user's side. We were able to successfully simulate the transaction at portalbridge.com. 

Thank you, @SamantaCasal.

Let us know if there's anything else we can help you with :)

**Comment by drisAloma** [comment] 2023-08-29 20:44
Okay noted!
Thanks guys 🙏🏽
But I am having the same issue too and I have been able to redeem some transactions for some users previously on my end.

**Comment by drisAloma** [comment] 2023-08-29 20:54
The "Transaction(s) simulation reverted" message comes up on the fourth approval prompt.

**Comment by sebastianscatularo** [comment] 2023-08-29 20:55
could be an issue with the RPC that you are using, you could try changing it in your wallet

**Comment by sebastianscatularo** [comment] 2023-08-29 20:56
or you could try with a VPV from a different location

**Comment by sebastianscatularo** [comment] 2023-08-30 17:40
@SamantaCasal, could we try to redeem this and see if the error arises?

**Comment by SamantaCasal** [comment] 2023-08-30 17:44
@ss3388 Could you give me the txId? 🙏

**Comment by Dahtank** [comment] 2023-09-02 23:51
I believe the 2 TXIDs are
Polygon -> Solana
TXID: 0x02d1ad0c4bf987963835411929dc8b55ff32ef8f1c4120ab558302c21d90a73a
Optmism -> Solana
TXID: 0x5fb4a0f0c591a6b4dc6ca2aae771e3162e194bfbb67091af59c75db6140e69f7

**Comment by drisAloma** [comment] 2023-09-11 17:31
Hello, 
Both reported transactions now shows "Success! The redeem transaction was submitted." on the bridge UI but the redeem transaction hashes are undefined on the target chain "Solana". Has it been resolved regardless?

Redeem tx: 0xbc27242a9ae93903f341839c15aac7af790b0c0144cb67cb3fb820c1f8b4cd2f
It is the same for both transactions.

@SamantaCasal @sebastianscatularo

**Comment by Dahtank** [comment] 2023-09-20 07:42
Following up on this as its been a month and there are 3 tickets related to this

**Comment by SamantaCasal** [comment] 2023-09-29 18:20
@yuli-ferna The bug still happens in https://preview.portalbridge.com/addd1f8564/#/transfer version. 
Evidence: 

https://github.com/XLabs/portal-bridge-ui/assets/69044575/4223245c-1d8b-4734-a9e5-8d961484147e

**Comment by SamantaCasal** [comment] 2023-10-02 13:40
@yuli-ferna 
 Re-test: the issue happens using  using metamask/phantom,

https://github.com/XLabs/portal-bridge-ui/assets/69044575/562dac7b-42aa-4034-9c0c-1a8e8c391116

**Comment by Dahtank** [comment] 2023-10-17 07:42
Any updates for this issue? 🙏🏽

**Comment by drisAloma** [comment] 2023-10-31 16:35
Hello,
Both issues have been resolved, thank you!

**Closed** 2023-11-29 13:18 UTC
Labels: bug, high
