### ISSUE TITLE
[QA][High]"Execution reverted: SafeERC20: approve from non-zero to non-zero allowance" shown in the console for TX from Arbitrum 

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#112] opened 2023-05-10 07:45 UTC
Preconditions: 
1. Wallet is connected
2. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://6d624a29.portal-bridge-ui.pages.dev/#/transfer

Steps:
1. Prepare to transfer 0.00001 tBTC from Arbitrum to Polygon/ Optimism
2. Click Next
3. Approve the required actions in wallet pop-up notification
4. Click button Transfer and Confirm on the transfer window
5. Observe

Actual result: Both me and Tatjana observed this behaviour:
* Transaction does not proceed after user clicks on "Transfer" button, waited >20 min
* Confirmation or approval notification is not displayed and there is no indication when manually opening wallet extension
* Error in Console: "SafeERC20: approve from non-zero to non-zero allowance"

Expected result: tBTC token is transferred.

Comments: Issue was not reproduced for transfer Arbitrum -> Ethereum

Attachment:
<img width="1365" alt="Screenshot 2023-05-10 at 10 33 08" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/d3f7f209-2404-4b72-a3f8-f9b38b50fba5">

Tatjana TX screenshot:
![Screenshot_2023-05-10_at_09 57 54](https://github.com/XLabs/portal-bridge-ui/assets/91047061/fa9497b9-7690-40de-bc64-6a49e0092a88)

**Comment by scnale** [comment] 2023-06-12 22:59
The cause for this particular problem should be fixed since some time ago. Reopen if that's not the case.

**Closed by scnale** 2023-06-12 22:59 UTC
Labels: bug
