### ISSUE TITLE
Claimed 11196 - can't bridge from Kujira to Solana

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#580] opened 2023-12-06 17:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
ERROR WITH TRANSFER, PLEASE TRY AGAIN. 

SETUP : 

LEAP WALLET
GOOGLE CHROME
NO VPN
```

### Current Behavior

![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/9161cb44-331b-47de-ad31-0e440031b485)
![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/0c752a89-e6bd-4b96-8dd0-f9b4ecdafb11)

**Comment by sebastianscatularo** [comment] 2023-12-12 22:58
@SamantaCasal could you try to bridge from Kujira to Solana and see if you can reproduce this?

**Comment by sebastianscatularo** [comment] 2023-12-12 23:00
seems to be duplicated of hhttps://github.com/XLabs/portal-bridge-ui/issues/582

**Comment by SamantaCasal** [comment] 2023-12-13 18:32
Tested from:
https://portalbridge.com/
OK! Sending wSol from Kujira -> Solana
[wormholesacn](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/2625)
[explorerSoana](https://explorer.solana.com/tx/2sdHfFmBGfjQ236zVX5rVnNfiDdU518ua5RQfwsfhSMceMSBfqRAQxpsmJcQARiG1vEu3GqnPEd9eppGsQcBDWbV)
[kujiraFinder](https://finder.kujira.network/kaiyo-1/tx/0EC3E1F9D4545A1646DA590F7317992C2A1D78CD69972E27BA57702C57EF38A5)

Evidence


https://github.com/XLabs/portal-bridge-ui/assets/69044575/144c2cd6-fb40-4e2b-8d23-0a9418261a60

**Comment by sebastianscatularo** [comment] 2023-12-13 18:44
@dry2022 could you ask the user to retry, since seems to be working, thanks @SamantaCasal

**Comment by sebastianscatularo** [comment] 2023-12-19 19:42
@dry2022 closing it since it was verified and seems to be working fine, please if you are still facing the issue create a new ticket

**Closed by sebastianscatularo** 2023-12-19 19:42 UTC
Labels: medium, needs triage, wormhole-support
