### ISSUE TITLE
[support]Cosmos Bridge: OSMO balance does not load up<ticket-9455>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#445] opened 2023-09-25 16:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: OSMOSIS 
- Source Chain Wallet:Kepler
- Target Chain: Solana 
- Target Chain Wallet: Phantom
- Asset Type: Token 
- Tx:
```

### Current Behavior

Does not load up balances on attempt to transfer $OSMO or $INJ token to Solana.

https://github.com/XLabs/portal-bridge-ui/assets/64994788/0ecb4007-0f7d-4c96-a59f-9a6e75f3120c

### Expected Behavior

Should display the current wallet balance on the cosmos bridge UI

### Steps To Reproduce

- Go to https://www.portalbridge.com/cosmos/
- Choose Osmosis as source and connect Kepler wallet

### Anything else?

When you reverse the route i.e Solana to Osmosis, balances on Solana chain loads up on the UI.

**Comment by sebastianscatularo** [comment] 2023-09-28 21:35
@drisAloma I'm following this issue with the Connect team, I was able to reproduce it, and it seems to be an issue with the Connect component

**Comment by sebastianscatularo** [comment] 2023-09-28 21:37
@drisAloma OSMO native token is not supported yet by Connect, so, this is working as expected, closing it now. :) thank you for contacting us.

**Closed by sebastianscatularo** 2023-09-28 21:37 UTC
Labels: medium, needs triage, wormhole-support

**Comment by drisAloma** [comment] 2023-09-28 21:39
Okay noted!
Thank you, I suspect the same goes for $INJ too.

**Comment by sebastianscatularo** [comment] 2023-09-28 21:56
yes, that's right
