### ISSUE TITLE
TICKET 9279 - can't bridge from SUI to OSMOSIS (got error) 

### ISSUE THREAD

**Issue by dry2022** [XLabs/portal-bridge-ui#390] opened 2023-09-07 14:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
Can't bridge SUI TO COSMOS 

CHROME 
NO VPN 
MARTIAN & SUIET
```

### Current Behavior

![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/ea502ee1-da12-4909-97a5-5da1a6320345)
![image](https://github.com/XLabs/portal-bridge-ui/assets/102968460/316bb7a9-3527-4e88-95a3-743dd23bf8ec)

### Steps To Reproduce

want to bridge from SUI to OSMOSIS via https://portalbridge.com/cosmos/

**Comment by SamantaCasal** [comment] 2023-09-07 18:22
Hi @dry2022 I made several attempts using the same wallets and token, but I couldn't reproduce the issue, could you tell me if there is any step or information to take into account besides what is described in the ticket?
I leave you some videos of evidence.
[Tx1:suiExplorer](https://suiexplorer.com/txblock/39V5Q8ZJ2cXtxTxFP9CxDcwjsEj3u5iyijjKx5XbcFHQ?network=mainnet)
[Tx1: mitScan](https://www.mintscan.io/osmosis/transactions/644FA875A9CBD7EC8D89481AE4F7EA6C22891D6331CD7E99C3E6AEED83F43B7D)

https://github.com/XLabs/portal-bridge-ui/assets/69044575/954ed7cf-8c37-4f0a-aafd-3de5a2c779e2

**Comment by willis20188** [comment] 2023-09-08 00:59
User feedback:
![image](https://github.com/XLabs/portal-bridge-ui/assets/83527164/c28571f4-f9cd-4193-b96a-12e8ec646601)

**Comment by sebastianscatularo** [comment] 2023-09-08 12:02
closing this, thank you @willis20188 :)

**Closed by sebastianscatularo** 2023-09-08 12:02 UTC
Labels: medium, needs triage, wormhole-support
