### ISSUE TITLE
[support] Ticket 2107 - User unable to select token from source chain Kujira to other chains

### ISSUE THREAD

**Issue by sleepycorgi1** [XLabs/portal-bridge-ui#642] opened 2024-01-04 12:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain:Kujira 
- Source Chain Wallet: kujira1u7dv7w2pnre7pgdfqa5gjzxyl7gnvqhtyk65x6
- Target Chain: 
- Target Chain Wallet:
- Asset Type:  (factory/wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx/4gn1J9pchUGh63ez1VwiuTmU4nfJ8Rr8o5HgBC5TMdMk)
- Tx: N/A 

First tx from polygon > kujira (already redeemed) : https://wormholescan.io/#/tx/0x8abdc6021e1ee100d9b52b8e52d6c426c8825592993496bc7d83bbc178cbe0e1
```

### Current Behavior

Token selector continously loading, token also does not appear when pasting in token contract code 
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/5eb7c0bd-5640-4fb6-95b5-bb26462c7c06)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/20c47b99-1ae2-4fae-991d-a83c3e3698b9)

### Expected Behavior

User should be able to select token

**Comment by sleepycorgi1** [comment] 2024-01-04 13:11
Ticket 2209 - User unable to load token selector from kujira  
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/9a8e9e11-f336-476c-aaf4-9d9028098c34)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/813cbe46-1ff0-4d60-84b9-042d43b9c212)

**Comment by sleepycorgi1** [comment] 2024-01-04 13:24
Ticket 2530 
Unable to send tokens back from Kujira  
token - factory/wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx/HJk1XMDRNUbRrpKkNZYui7SwWDMjXZAsySzqgyNcQoU3
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/4bef94f8-0404-45a0-8b5a-7ac18c32fa29)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/ba86d4c7-2931-462a-9bbb-cb16e8b5da25)


original tx from sol  to kujira : 57kKttgFbGQHitbPb6UKvCdAbWzqaN3N3zSkvGU7J7hHQSTQ7RoGJfF9k5amVJRQqhbpNXKPzPPMg1LjFUW844kL 

arrived kujira : https://finder.kujira.network/kaiyo-1/tx/67694D685FD63F25703E2E8F4A812660C60A785CD88EC93785DB7FA99E43D5D8

**Comment by sleepycorgi1** [comment] 2024-01-04 13:26
Ticket 2526 - 
Unable to bridge token out from Kujira 
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/4ab5568a-589b-477c-8aac-bdbe55f489c7)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/fe60cf9f-d4fd-4650-86a9-70adf9e0569
2)

transaction from arb > kujira : 0xf25ac1d77e5ed19e632c05b778a850f730605cdbc71ba3bc45ee3bd7bc429149
Transaction arriving on kujira: https://finder.kujira.network/kaiyo-1/tx/A44F338C5048D90053B97233AC42645F5F983ADD3CDB930975B548597AE83B4F

**Comment by yuli-ferna** [comment] 2024-01-04 21:18
In the case of kujira that the problem is on the service side of the rpc. Similar case with https://github.com/XLabs/portal-bridge-ui/issues/575

**Comment by drisAloma** [comment] 2024-01-04 22:01
Hello @yuli-ferna 
Does the mean the users have to wait for a fix or there is a way they can change the rpc on their ends?

A lot of users are facing this issue and some are quite dramatic.

Ticket-2613 & 2670 are experiencing the same now.

**Comment by yuli-ferna** [comment] 2024-01-04 23:05
@drisAloma we are evaluating these two options, if we can't change the rpc, we have to wait for a fix. I will keep you informed

**Comment by willis20188** [comment] 2024-01-08 00:56
Ticket 3042 
Unable to bridge token out from Kujira
![1](https://github.com/XLabs/portal-bridge-ui/assets/83527164/8e610f04-a655-42f2-ad0f-85ee64f2bb9b)
![1](https://github.com/XLabs/portal-bridge-ui/assets/83527164/ed33cbf2-72f1-4c3a-a624-3ff094eb65cd)

transaction from arb > kujira (already redeemed): 0x8a4448ffb60d73405267fb5c4a14df9c49b4b2f7d4ce218071823678802c5390

**Comment by yuli-ferna** [comment] 2024-01-08 14:23
@sleepycorgi1 @drisAloma @willis20188 Now the users must be able to see their balances

**Comment by yuli-ferna** [comment] 2024-01-15 18:31
Since there have been no new reports I will close the issue

**Closed by yuli-ferna** 2024-01-15 18:31 UTC
Labels: medium, needs triage, wormhole-support
