### ISSUE TITLE
[support] Redeem Transaction Failed : "Unknown Error Occurred" (there is enough SOL for gas) <ticket-9055>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#340] opened 2023-08-24 19:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Ethereum
- Source Chain Wallet: Metamask
- Target Chain: Solana
- Target Chain Wallet: Phantom
- Asset Type: Token
- Asset: WETH
- Tx:https://etherscan.io/tx/0x8d282503427b099ad57ba7e7be5c321ec26395730af1082b037be86045346049
```

### Current Behavior

It is still showing that the transaction needs to be redeemed on the user's end and throws the error after the fourth approval prompt but shows "the redeem transaction was submitted" on my end.
![Failed_redemption](https://github.com/XLabs/portal-bridge-ui/assets/64994788/269c9505-7b93-445d-8cad-cff2f6be1111)
![highlight_tx](https://github.com/XLabs/portal-bridge-ui/assets/64994788/f22d1bd0-a844-4e7c-b409-f5d76854b7e4)

### Steps To Reproduce

Redeem workflow

### Anything else?

The submitted redemption transaction shows USDC token instead of WETH
https://solscan.io/tx/5pwBJ4h5ufQEm2w5fZGGeeigFQYYrVer8TMBWL3xpyhyoEMcMG3r5EGJ4VJBWgrp5T9CzpbffNCiKBC8JTv9HhnU

**Comment by sebastianscatularo** [comment] 2023-08-25 13:24
@SamantaCasal could you try to reproduce this issue?

**Comment by SamantaCasal** [comment] 2023-08-25 15:16
I can't reproduce it yet. I tested the same scenario, and the tx carried out OK. 
FYI: @sebastianscatularo 
Evidence: 
Source [Eth](https://etherscan.io/tx/0xf5448fa43a359cb783a1d862162fbdc81bc2ecacdad222287c034d46533ad0ca)
Target [SOL](https://solscan.io/tx/2tKH1VRcnzRPTyE2jrfdQNqxuzu8Ft6D7yc5bn1kcHZH2RqSSLfn42W5pXiGwbjd8Q4A8zyqLgbRpzB24yAotsgn)
Record: 
Part 1

https://github.com/XLabs/portal-bridge-ui/assets/69044575/2fa5150e-428c-4475-acb1-8f3223c40092

Part 2

https://github.com/XLabs/portal-bridge-ui/assets/69044575/2af6ed23-2b32-411c-b194-e13234d3d97f

![Screenshot 2023-08-25 at 12 03 41 PM](https://github.com/XLabs/portal-bridge-ui/assets/69044575/866185cb-d3a2-48b5-aa7a-f3796b6b0dcd)

**Comment by sebastianscatularo** [comment] 2023-08-25 15:25
@SamantaCasal could you try the following?

- Go to: 
https://www.portalbridge.com/recovery/ethereum/0x8d282503427b099ad57ba7e7be5c321ec26395730af1082b037be86045346049
- Connect your wallet
- hit recovery

and from there try to redeem it

and please record the console logs

**Comment by SamantaCasal** [comment] 2023-08-25 15:33
@sebastianscatularo Here: 
[TX on SOLSCAN](https://solscan.io/tx/5g6iUwonK4v3iFXkcxZ4KDbLALe4dEprHtv7qYz1w1UEJvZkKYdPs1vmmMGWiYsh8WW4mFxh8j4Q2frRTwJ3QSta)

https://github.com/XLabs/portal-bridge-ui/assets/69044575/e05bd491-d4fd-40e3-8a25-25acb4b07113

2 Chance

https://github.com/XLabs/portal-bridge-ui/assets/69044575/9a2bb64e-b37a-4076-b964-51fbe337b14a

**Comment by drisAloma** [comment] 2023-08-25 16:03
Thanks guys!
The user got the tokens in destination wallet.

**Comment by sebastianscatularo** [comment] 2023-08-25 16:34
@drisAloma closing this

**Closed by sebastianscatularo** 2023-08-25 16:34 UTC
Labels: medium, needs triage, wormhole-support
